site_name: FIWARE Showcase Evaluation
site_url: https://fiware-marketplace.readthedocs.org
repo_url: https://github.com/FIWARE-Ops/docs.marketplace-evaluation
site_description: FIWARE Showcase Evaluation
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
extra_css:
  - 'https://fiware.github.io/catalogue/style/fiware_readthedocs.css'
  - 'https://fiware.github.io/catalogue/style/fiware_readthedocs_neutral.css'
nav:
  - Home: index.md
  - Powered by FIWARE Solution:
      - 'How to Apply': solution/apply.md
      - 'Guidelines': solution/guideline.md
  - Powered by FIWARE Platform:
      - 'How to Apply': platform/apply.md
      - 'Guidelines': platform/guideline.md
  - FIWARE-Ready IoT Device:
      - 'How to Apply': 'device/apply.md'
      - 'Guidelines': 'device/guideline.md'
      - 'Test Scenarios': 'device/test-scenarios.md'
  - FIWARE-Ready Software Enabler:
      - 'How to Apply': 'enabler/apply.md'
      - 'Guidelines': 'enabler/guideline.md'
  - FIWARE Consultancy Services:
      - 'How to Apply': 'consulting/apply.md'
      - 'Guidelines': 'consulting/guideline.md'
  - FIWARE Training Providers:
      - 'How to Apply': 'training/apply.md'
      - 'Guidelines': 'training/guideline.md'
